[package]
name = "netcode"
version = "0.1.0"
authors = ["Val Vanderschaegen <valere.vanderschaegen@gmail.com>"]
build = "build.rs"
links = "libnetcode"

[dependencies]

[build-dependencies]
gcc = "0.3.43"